services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag_de_notas_qdrant

    restart: unless-stopped

    ports:
      - "6333:6333"

    volumes:
      - ./data/qdrant:/qdrant/storage